function getSearchResults() {
        var course_hash = {
        'ANTH 210': {
            'name': 'Eating Culture',
            'term': '1',
            'days': 'T&nbsp;Th',
            'time': '14:00-15:30',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['ethnic studies +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ANTH&course=210&section=001',
            'subj' : 'ANTH',
            'fac'  : 'Arts',
        },
        'ANTH 217': {
            'name': 'Culture and Communication',
            'term': '1',
            'days': 'T&nbsp;Th',
            'time': '12:30-14:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['ethnic studies +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ANTH&course=210&section=001',
            'subj' : 'ANTH',
            'fac'  : 'Arts',
        },
        'ANTH 407': {
            'name': 'Principles of Field Work',
            'term': '2',
            'days': 'T&nbsp;Th',
            'time': '15:30-17:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['field methods +2', 'ethnic studies +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ANTH&course=407&section=001',
            'subj' : 'ANTH',
            'fac'  : 'Arts',
        },
        'ANTH 418': {
            'name': 'Anthropological Statistics',
            'term': '1',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '15:00-16:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['math +2', 'ethnic studies +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ANTH&course=418&section=201',
            'subj' : 'ANTH',
            'fac'  : 'Arts',
        },
        'ASTR 101': {
            'name': 'Introduction to the Solar System',
            'term': '1',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '12:00-13:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['math +2', 'exp methods +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ASTR&course=101&section=101',
            'subj' : 'ASTR',
            'fac'  : 'Science',
        },
        'ASTR 102': {
            'name': 'Introduction to Stars and Galaxies',
            'term': '2',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '12:00-13:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['math +2', 'exp methods +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ASTR&course=102&section=201',
            'subj' : 'ASTR',
            'fac'  : 'Science',
        },
        'ASTR 310': {
            'name': 'Exploring the Universe I: The Solar System',
            'term': '1',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '12:00-13:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': false,
            'skills': ['math +2', 'exp methods +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ASTR&course=310&section=101',
            'subj' : 'ASTR',
            'fac'  : 'Science',
        },
        'ASTR 311': {
            'name': 'Exploring the Universe II: Stars and Galaxies',
            'term': '2',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '12:00-13:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': false,
            'skills': ['math +2', 'exp methods +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ASTR&course=311&section=201',
            'subj' : 'ASTR',
            'fac'  : 'Science',
        },
        'ASTR 406': {
            'name': 'High-Energy Astrophysics',
            'term': '2',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '13:00-14:00',
            'cred': 3,
            'eligible1': false,
            'eligible2': false,
            'skills': ['math +2', 'exp methods +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ASTR&course=406&section=101',
            'subj' : 'ASTR',
            'fac'  : 'Science',
        },
        'BIOL 300': {
            'name': 'Fundamentals of Biostatistics',
            'term': '1',
            'days': 'T&nbsp;Th',
            'time': '14:00-15:30',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['exp methods +2', 'collab +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=BIOL&course=300&section=101',
            'subj' : 'BIOL',
            'fac'  : 'Science',
        },
        'BIOL 301': {
            'name': 'Biomathematics',
            'term': '1',
            'days': 'T&nbsp;Th',
            'time': '8:00-9:30',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['exp methods +2', 'math +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=BIOL&course=301&section=101',
            'subj' : 'BIOL',
            'fac'  : 'Science',
        },
        'CPSC 344': {
            'name': 'Introduction to Human Computer Interaction Methods',
            'term': '1',
            'days': 'M&nbsp;W',
            'time': '16:00-17:30',
            'cred': 3,
            'eligible1': false,
            'eligible2': false,
            'skills': ['collab +2', 'computing/tech +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=CPSC&course=344&section=101',
            'subj' : 'CPSC',
            'fac'  : 'Science',
        },
        'HIST 350': {
            'name': 'The Soviet Union',
            'term': '2',
            'days': 'M',
            'time': '18:00-21:00',
            'cred': 6,
            'eligible1': true,
            'eligible2': true,
            'skills': ['ethnic studies +3', 'writing +3'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=HIST&course=350&section=001',
            'subj' : 'HIST',
            'fac'  : 'Arts',
        },

        'COMM 100': {
            'name': 'Introduction to Business',
            'term': '2',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '9:00-10:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['collab +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=COMM&course=100&section=201',
            'subj' : 'COMM',
            'fac'  : 'Business (Sauder)',
        },
        'COMM 204': {
            'name': 'Logistics and Operations Management',
            'term': '2',
            'days': 'M&nbsp;F',
            'time': '8:30-10:00',
            'cred': 3,
            'eligible1': false,
            'eligible2': false,
            'skills': ['collab +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=COMM&course=204&section=201',
            'subj' : 'COMM',
            'fac'  : 'Business (Sauder)',
        },
        'COMM 205': {
            'name': 'Introduction to Management Information Systems',
            'term': '1',
            'days': 'W&nbsp;F',
            'time': '8:30-10:00',
            'cred': 3,
            'eligible1': false,
            'eligible2': false,
            'skills': ['collab +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=COMM&course=205&section=101',
            'subj' : 'COMM',
            'fac'  : 'Business (Sauder)',
        },
        'COMM 438': {
            'name': 'Management of Information Systems',
            'term': '1',
            'days': 'T&nbsp;Th',
            'time': '9:30-11:00',
            'cred': 3,
            'eligible1': false,
            'eligible2': false,
            'skills': ['collab +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=COMM&course=438&section=101',
            'subj' : 'COMM',
            'fac'  : 'Business (Sauder)',
        },
        'POLI 100': {
            'name': 'Introduction to Politics',
            'term': '1',
            'days': 'T&nbsp;Th',
            'time': '11:00-12:30',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['collab +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=POLI&course=100&section=001',
            'subj' : 'POLI',
            'fac'  : 'Arts',
        },
        'POLI 101': {
            'name': 'The Government of Canada',
            'term': '1',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '11:00-12:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['collab +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=POLI&course=101&section=001',
            'subj' : 'POLI',
            'fac'  : 'Arts',
        },
        'THTR 130': {
            'name': 'Introduction to Stage Acting',
            'term': '1',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '10:00-11:00',
            'cred': 3,
            'eligible1': true,
            'eligible2': true,
            'skills': ['collab +2', 'performance +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=THTR&course=130&section=001',
            'subj' : 'THTR',
            'fac'  : 'Arts',
        },
        'GEOG 311': {
            'name' : 'Urban Environments',
            'term' : '2',
            'days' : 'T&nbsp;Th',
            'time' : '14:00-15:30',
            'cred' : 3,
            'eligible1' : true,
            'eligible2' : true,
            'skills' : ['field methods +2', 'writing +1'],
            'link' : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=GEOG&course=311&section=201',
            'subj' : 'GEOG',
            'fac' : 'Arts',
        },
        'GEOG 327': {
            'name'      : 'Creating Canada',
            'term'      : '1',
            'days'      : 'T&nbsp;Th',
            'time'      : '12:30-14:00',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : true,
            'skills'    : ['collab +2', 'writing +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=GEOG&course=327&section=101',
            'subj'      : 'GEOG',
            'fac'       : 'Arts',
        },
        'GEOG 328': {
            'name'      : 'Constructing Canada',
            'term'      : '2',
            'days'      : 'T&nbsp;Th',
            'time'      : '09:30-11:00',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : true,
            'skills'    : ['collab +2', 'writing +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=GEOG&course=328&section=201',
            'subj'      : 'GEOG',
            'fac'       : 'Arts',
        },
        'ASTU 360': {
            'name'      : 'Community-Based Research and Knowledge Creation',
            'term'      : '2',
            'days': 'M&nbsp;W&nbsp;F',
            'time': '10:00-11:00',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : true,
            'skills'    : ['collab +2', 'field methods +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ASTU&course=360&section=03C',
            'subj'      : 'ASTU',
            'fac'       : 'Arts',
        },
        'ASTU 210': {
            'name'      : 'Global Citizenship, Part 1: Introduction',
            'term'      : '2',
            'days'      : 'T&nbsp;Th',
            'time'      : '13:00-14:30',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : true,
            'skills'    : ['collab +2', 'ethnic studies +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=ASTU&course=210&section=001',
            'subj'      : 'ASTU',
            'fac'       : 'Arts',
        },
        'FNH 330': {
            'name'      : 'Introduction to Wine Science 1',
            'term'      : '1',
            'days'      : 'T&nbsp;Th',
            'time'      : '16:00-17:00',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : false,
            'skills'    : ['ethnic studies +2', 'exp methods +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=FNH&course=330&section=001',
            'subj'      : 'FNH',
            'fac'       : 'Land and Food Systems',
        },
        'EOSC 310': {
            'name'      : 'The Earth and the Solar System',
            'term'      : 'A',
            'days'      : 'N/A',
            'time'      : 'N/A',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : false,
            'skills'    : ['writing +2', 'field methods +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=EOSC&course=310&section=99A',
            'subj'      : 'EOSC',
            'fac'       : 'Science',
        },
        'EOSC 311': {
            'name'      : 'The Earth and its Resources',
            'term'      : 'C',
            'days'      : 'N/A',
            'time'      : 'N/A',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : false,
            'skills'    : ['field methods +2', 'writing + 1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=EOSC&course=311&section=99C',
            'subj'      : 'EOSC',
            'fac'       : 'Science',
        },
        'EOSC 314': {
            'name'      : 'The Ocean Environment',
            'term'      : 'A',
            'days'      : 'N/A',
            'time'      : 'N/A',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : false,
            'skills'    : ['field methods +2', 'collab +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=EOSC&course=314&section=99A',
            'subj'      : 'EOSC',
            'fac'       : 'Science',
        },
        'EOSC 315': {
            'name'      : 'The Ocean Ecosystem',
            'term'      : '2',
            'days'      : 'M&nbsp;W&nbsp;F',
            'time'      : '14:00-15:00',
            'cred'      : 3,
            'eligible1' : true,
            'eligible2' : false,
            'skills'    : ['field methods +2', 'collab +1'],
            'link'      : 'https://courses.students.ubc.ca/cs/main?pname=subjarea&tname=subjareas&req=5&dept=EOSC&course=315&section=201',
            'subj'      : 'EOSC',
            'fac'       : 'Science',
        },
        'order': ['ANTH 210', 'ANTH 217', 'ANTH 407', 'ANTH 418', 'ASTR 101', 'ASTR 102', 'ASTR 310', 'ASTR 311', 'ASTR 406',
                  'ASTU 210', 'ASTU 360', 'BIOL 300', 'BIOL 301', 'COMM 100', 'COMM 204', 'COMM 205', 'COMM 438',
                  'CPSC 344', 'EOSC 310', 'EOSC 311', 'EOSC 314', 'EOSC 315', 'FNH 330', 'GEOG 311', 'GEOG 327', 'GEOG 328',
                'HIST 350', 'POLI 100', 'POLI 101', 'THTR 130']
    };

    return course_hash;
}

// Template for adding new courses
// 'AAAA 000': {
//     'name'      :
//     'term'      :
//     'days'      :
//     'time'      :
//     'cred'      :
//     'eligible1' :
//     'eligible2' :
//     'skills'    :
//     'link'      :
//     'subj'      :
//     'fac'       :
// },
